# Las variables se definiran en el archivo .env
version: '3'
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
services:
  php:
  # Path to a directory containing a Dockerfile. When the value supplied
  # is a relative path, it is interpreted as relative to the location of
  # the yml file itself. This directory is also the build context that is
  # sent to the Docker daemon.
  #
  # Compose will build and tag it with a generated name, and use that image
  # thereafter.
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-php
    # Se expone el puerto-> puerto el cual queda expuesto : puerto dentro del servicio
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
  mysql:
  # Imagen que se usara para construir el servicio
    image: mysql/mysql-server:8.0.27
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    # Se asignan variables de entorno
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3306
    # Se expone el puerto-> puerto el cual queda expuesto : puerto dentro del servicio
    ports:
      - "3306:3306"
    restart: always


