version: '3'

services:
  php:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql/mysql-server:8.0.27
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    restart: always


