# todas las variables usadas en este archivo son del archivo .env
# (build: .) se usa para cuando el archivo Dockerfile esta en el mismo del docker-compose.yml
version: '3'

services:
  app:
    build:
      # Envia la variable ${PHP_VERSION} al Dockerfile de la ruta ./docker/php
      # en ese archivo se construira la imagen para este contenedor
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    image: php-apache
    container_name: ${APP_PROJECT_NAME}
    # Se expone el puerto-> puerto el cual queda expuesto : puerto dentro del servicio
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
  mysql:
  # Imagen que se usara para construir el servicio
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    # se deja el "image" para darle un nombre especifico a la imagen al momento de crearlo 
    image: 8.0.27
    #image: mysql/mysql-server:8.0.27
    container_name: ${DB_PROJECT_NAME}
    # Se asignan variables de entorno
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: 3306
    # Se expone el puerto-> puerto el cual queda expuesto : puerto dentro del servicio
    ports:
      - "3306:3306"
    restart: always


